### ISSUE TITLE
Organizing and optimizing the scripts file

### ISSUE THREAD

**Issue by LabinatorSolutions** [LabinatorSolutions/boldchess-web-app#12]
All the JS codes at the moment are in one file. For better development, that big file should be broken down into a set of files. That will greatly help new contributors and developers in adjusting to the codes and fixing bugs. The file right now is very big and not easy to read.

**Comment by i-iurchuk** [comment]
@LabinatorSolutions Hi! 

I want to participate in the project. But I have a couple of questions.
1. Does the new project version have to be on a Vanilla JS or can frameworks be used (as for example React)?
2. I see that an outdated code specification is being used, and I would like to use a newer one (ES6/ES7).
3. JavaScript or TypeScrypt? 🙂

**Comment by LabinatorSolutions** [comment]
@i-iurchuk 

Thank you for your interest in contributing and being part of our team.

You are free to improve on the scripts in any way you like. You are free to use frameworks, libraries, and even upgrade the code specifications. No restrictions whatsoever.

We do prefer JavaScript over TypeScript but we won't restrict you if you like to use TypeScript.

Thank you once again for joining us.

All the best!

**Comment by i-iurchuk** [comment]
@LabinatorSolutions Sorry, forced to abandon this task.

**Comment by LabinatorSolutions** [comment]
@i-iurchuk It's all cool. We have already assumed that you did :)

**Comment by LabinatorSolutions** [comment]
@resparx : Thank you for your contribution.

**Comment by LabinatorSolutions** [comment]
@resparx The bundle.js is not found. The paths to the files also require fixing in the (index.html) file. The browser is also complaining about: "Uncaught SyntaxError: Cannot use import statement outside a module". It would be nice to fix the above and submit a new pull request. Thanks

**Comment by resparx** [comment]
hey @LabinatorSolutions , i cant see my change in the code, which i gave 21 days back. Is it been reverted?

**Comment by LabinatorSolutions** [comment]
@resparx : We are sorry to inform you that we have indeed reverted it since we have no time to debug your changes. It was also clear to us that you were not testing the app before submitting the pull request. 

This application is designed to be used by the absolute beginners who don't even know JavaScript. The HTML file is very important to be present in the root directory since beginners don't even know how to call a file in a subdirectory or how to compile a JS application. The objective is for the app to work out-of-box without any attention from the end-user.

Please move the HTML file back to the root folder, and check what errors your browser is giving when you do so. Adjust the path URLs and **make sure to test the app well by moving the pieces and checking the buttons** before you submit a new pull request.

Thank you for your understanding and contribution.

**Comment by LabinatorSolutions** [comment]
This issue has been addressed in the latest commit.
